### ISSUE TITLE
Allow async messaging

### ISSUE THREAD

**Issue by archer884** [SBSTP/hiirc#8]
Some of my messages depend on (occasionally slow) third party web API calls. I'd prefer that these not block normal operation while they run, and so it seems like some means of sending a message without an `&Irc` would be nice.

**Comment by clux** [comment]
I am noticing this too. If you sleep for 5 minutes in one of the message callbacks the client will time out.
Maybe the callbacks can receive a thread safe `Irc` handle, which would allow us to spawn threads for this stuff in the callbacks.

**Comment by sbstp** [comment]
I added the [DefferedWriter](http://sbstp.github.io/hiirc/hiirc/struct.DeferredWriter.html) a couple weeks ago. It's not an ideal solution, but it works. I'd like to explore more solutions.

EDIT: You can get a DefferedWriter via `irc.deffered()`.

**Comment by sbstp** [comment]
I like your idea of making `Irc` thread safe, the only issue I have is that `Irc` contains the data on channels and users. It will require exposing parts of the `RwLock` API.

Also the data when the thread was spawned might differ from what it is once the thread is done processing. Example: user asks for data, thread is spawned, http request is sent, user leaves, http response is received, send result to user, but they're gone.

**Comment by sbstp** [comment]
I've worked on a [prototype](https://github.com/sbstp/hiirc/commit/20191f9acee66647ad704883990b0557ec4a3a94), I'd like to have your opinions. Channels, users and even some strings have been `Arc`'d. Fine grained control of mutability was added where needed, using mutexes.

**Comment by clux** [comment]
That looks interesting. I'll have a go at it when I get home.

It looks like you've `Arc`'d up a lot of things. My initial feel is that you perhaps do not need to sanitize `ChannelUser` and `Channel`, but rather just pass around copies as they were at the time. Listener based reactions typically just result in a raw string command going out on the wire anyway, and I doubt people are going to re-check if the user is still there before doing stuff like try to respond to him. Having a user potentially be gone inside a thread after you have calculated a response to that user, is possibly a bit of a bizarre thing to program for in every listener :)

On the other hand, since these live inside `Irc`, that may just have been the compiler required effect Arcing up `Irc`. Anyway, I'll look more into it later.

**Comment by clux** [comment]
I've tried using it now. It works works great with `thread::spawn`:

``` rust
    fn channel_msg(&mut self, irc: Arc<Irc>, channel: Arc<Channel>, user: Arc<ChannelUser>, msg: &str) {
        if msg.starts_with(NICKNAME) {
            self.blah += 1;
            let resp = format!("blah {}", self.blah);
            irc.privmsg("#clux", &resp); // channel.name is private so can't actually use it atm
            thread::spawn(move || {
                thread::sleep(std::time::Duration::from_secs(4));
                irc.privmsg("#clux", "done");
            });
        }
    }
```

This no longer starves the bot if you sleep for 5 minutes at least, and it can handle multiple requests. 

It does appear that even without sleeps messages from the bot is being throttled quite heavily? If I spam it with highlighting messages it will respond only to one at a time and with a 2s delay. I mean, that's probably sensible, but I can't find the part of your code that does this.

Also, at the moment the `Channel` struct appears to only have private members so the `channel_msg` listener cannot use it.

**Comment by sbstp** [comment]
> It does appear that even without sleeps messages from the bot is being throttled quite heavily? If I spam it with highlighting messages it will respond only to one at a time and with a 2s delay. I mean, that's probably sensible, but I can't find the part of your code that does this.

I'm not too sure what you mean by this. There's no voluntary throttling anywhere as far as I remember.

> Also, at the moment the Channel struct appears to only have private members so the channel_msg listener cannot use it.

I made the fields private, but added methods. The fields were made private because there's a lot of boilerplate now, mutexes and what not. The methods strip the unnecessary away. For `Channel` there's `name()`, `topic()`, `get_user(nickname)`, and `users()`.

**Comment by clux** [comment]
Here's an example of throttling using a basic handler:

``` rust
    fn channel_msg(&mut self, irc: Arc<Irc>, channel: Arc<Channel>, user: Arc<ChannelUser>, msg: &str) {
        if msg.starts_with(NICKNAME) {
            self.blah += 1;
            let resp = format!("blah {}", self.blah);
            irc.privmsg("#clux", &resp); // channel.name is private so can't actually use it atm
        }
    }
```

and output after spamming it:

``` sh
22:31:13        -- | Channel created on Wed, 02 Mar 2016 22:29:53
22:31:21      clux | zedonius: hi
22:31:21 @zedonius | blah 1
22:31:21      clux | zedonius: hi
22:31:21      clux | zedonius: hi
22:31:21      clux | zedonius: hi
22:31:21      clux | zedonius: hi
22:31:22      clux | zedonius: hi
22:31:22      clux | zedonius: hi
22:31:22      clux | zedonius: hi
22:31:22      clux | zedonius: hi
22:31:22      clux | zedonius: hi
22:31:24 @zedonius | blah 2
22:31:26 @zedonius | blah 3
22:31:28 @zedonius | blah 4
22:31:30 @zedonius | blah 5
22:31:32 @zedonius | blah 6
22:31:34 @zedonius | blah 7
22:31:36 @zedonius | blah 8
22:31:38 @zedonius | blah 9
22:31:40 @zedonius | blah 10
```

**Comment by sbstp** [comment]
I'm pretty sure that this is the server's doing. I've seen this before. If you try with another client library, do you also get this behavior?

**Comment by clux** [comment]
Oh, that could be. I've not used freenode much before. I'll check.

**Comment by clux** [comment]
Yeah, that's totally freenode. Sorry.

**Comment by sbstp** [comment]
Ok. No problem. I'll clean things up a bit and release 0.4.

**Comment by archer884** [comment]
Woohoo!

**Comment by sbstp** [comment]
I could also export some type declarations to lighten the boilerplate code. Something like `type Irc = Arc<core::Irc>`.

**Comment by sbstp** [comment]
Alright, it's all uploaded. I'll close the issue for now, don't hesitate to re-open / open another if you have more issues.

**Comment by clux** [comment]
Great work! Thank you very much!

One awesome thing I noticed is that since `ChannelUser` is also Arc'd and kept up to date, it will redirect messages correctly if I issue /nick before waiting for a response. Which is pretty cool. That had fooled all my previous irc libraries :)
